// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqcoWfzB6vL0En3AdK_yj-uClKPwzJPI',
    appId: '1:347301362281:web:db614ba96368fad7e200f8',
    messagingSenderId: '347301362281',
    projectId: 'qr-based-real-time-monitoring',
    authDomain: 'qr-based-real-time-monitoring.firebaseapp.com',
    storageBucket: 'qr-based-real-time-monitoring.firebasestorage.app',
    measurementId: 'G-MGVRDGHPZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeO4noPtdDjUhXti_rHxsNDSS9WE4nFdQ',
    appId: '1:347301362281:android:733902ee5d0a17bce200f8',
    messagingSenderId: '347301362281',
    projectId: 'qr-based-real-time-monitoring',
    storageBucket: 'qr-based-real-time-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0CfETq2pAIetU4kgrCVHnHjGVNpDb0k',
    appId: '1:347301362281:ios:0affbb8be05d03bae200f8',
    messagingSenderId: '347301362281',
    projectId: 'qr-based-real-time-monitoring',
    storageBucket: 'qr-based-real-time-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.waltermobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0CfETq2pAIetU4kgrCVHnHjGVNpDb0k',
    appId: '1:347301362281:ios:0affbb8be05d03bae200f8',
    messagingSenderId: '347301362281',
    projectId: 'qr-based-real-time-monitoring',
    storageBucket: 'qr-based-real-time-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.waltermobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOqcoWfzB6vL0En3AdK_yj-uClKPwzJPI',
    appId: '1:347301362281:web:86ac80be511eb173e200f8',
    messagingSenderId: '347301362281',
    projectId: 'qr-based-real-time-monitoring',
    authDomain: 'qr-based-real-time-monitoring.firebaseapp.com',
    storageBucket: 'qr-based-real-time-monitoring.firebasestorage.app',
    measurementId: 'G-QGPK5S893P',
  );
}
